language: node_js

node_js:
  - "node"
  - "lts/*"

env:
  global:
    - secure: twZO+xPqkYrHoZwxCTARwWYSV75di+fH7PdP4B2LZnEM7Ez70ubgdfJ7pmnhRtEfJq4KcfDvs/53YhxsqAXjqxegKW2cGvgOeFLoSjmjQtOcZC+ICmQTKtpq6dZp5CS88Cj8I7F5q+WBX3VyY8RIXU8sz96WiTaw1sbU0TeAlpYHyiKxQEQuf6Y/nk2zLmpx7j16g+Arr3NiCyLxxC8n0a/m7rYC8DeeVHzoIfeD91I7JNT8u/Y20bysf6ALLl9rHztIALG4m103HKKIcs6wgAUDw4jkSRogGWvRr9JOBIc38MLDLwDua4hj38Z91iAZS7yy62uRRL3WaGNJI0+ydy9FPrefjMqGtMXqWjBVdVOayCsYdIAOAVLw+sAkxkGdxDI3Nxe19SWbtvCTSqBblDSvm7HKzaKXVMKLIVymBY+ddMDj/UUUZr8ghIjL/7RBtcotKPmNEZ4F6Km4zOsx/MhPs4tR0Jtz64f2LN78PC1bCdSVwZN9mzmCAHO3fuI4u0GvDjhOmriLSmJWLxmmbfq6x36SE99OIjLJ/3i/OM5HLly1VdmZtxFZdbPZXdXrnAtPytKAZwpW2+XseU/QsGqT0ic2BqY+13VH8zlCIK9rvSa0oQPgp47LEAPIGxvBpIcE3alk/cij++ay8LuDEwDVJWzprnIUai9hHlkFBMo=
    - secure: C1jZXl6G+eO2nuJPO3tbigL+fO22p2qSlZi759E9GQimW/6In2y0N1WYHeuBQZlyKYCjHkSZGyeNygXCwJ1geX3YsEFRf5EAb8lIiMKxrYuRSg7Cz9cnFrpBpdbI2u9QCO6EdbOMBJOaLK6ZjbeAhcqfXZtX6Tjn40HPBuPxTgQSBMcvmoB72VxT1AVXuolks8mZvH42C+Ks5CQLKuiAb2KoK8B/eow/s7/ow/8cHhjrHki/jvaagk+lMlWr3FZxq2vBQzEBjcLWUllQmoTy41Pq3F+yYCQjpX3GxwU6l/krkvPDfjNEKLsDFVuZNhRp3B1keimXrwVf4J9i3AA+c//eR5JIpyaoqk1Y6yy89e7C5HC76Yaw1OKiOQ9J4eABx5cx2wDt59PDm1Cgegs2WFT30kN0sS/ZaoD7zRa7hHkDj9FNFkz4MF6UJnUIf2f2BZrmkKGrv0F1ujDV6YopnOpZ6VZMzX/uSu2ROu7AbpgAABZ/KNwPPag2zdGYBRHkgv0uJ5u6KwHIckaTERnl3Wp4BH9rNTHsX3DLsZdmn88fHe8OjEipnMIM/z7+6iTYHpPjQEKs+PwT+47OUkIpsABZ46WROSEHi/6KILJO16FkJZ2ArqcZ44/H6qSx5PVr5ohhQe8UpY7IB5eBw/PUGCMsjuOSBA6BL1Cw/NoRhIg=
  
before_script:
  - REPO_VERSION="$(npx -c 'echo "$npm_package_version"')"
  - echo "REPO_VERSION=$REPO_VERSION"
  - npm run build
  - GTMPLANT_VERSION="$(node dist/index.js -V)"
  - echo "GTMPLANT_VERSION=$GTMPLANT_VERSION"
  - NPM_PACKAGE_VERSION="$(npm view gtmplant version)"
  - echo "NPM_PACKAGE_VERSION=$NPM_PACKAGE_VERSION"
  - echo "TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST"
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH"
  - |
    if [ "$REPO_VERSION" != "$GTMPLANT_VERSION" ]; then
      echo -e '\033[0;31mPackage version and commander version must be the same.';
      travis_terminate 1;
    fi
  - |
    if [ "$TRAVIS_PULL_REQUEST" != "false" ] && [ "$TRAVIS_BRANCH" == "master" ] && [ "$REPO_VERSION" == "$NPM_PACKAGE_VERSION" ]; then
      echo -e '\033[0;31mPackage version must be higher than the current one.';
      travis_terminate 1;
    fi
  - npm run lint

jobs:
  include:
    - stage: "Github Deployment"
      if: branch = master AND type = push
      node_js: "lts/*"
      install: skip
      before_script: skip
      script: skip
      before_deploy:
        - REPO_VERSION="$(npx -c 'echo "$npm_package_version"')"
        - echo "REPO_VERSION=$REPO_VERSION"
        - git tag -f "$REPO_VERSION"
        - echo "New Tag $(git describe --tags)";
        
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN

    - stage: "npm Deployment"
      if: tag IS present
      node_js: "lts/*"
      before_script: skip
      script: skip
      deploy:
        provider: npm
        email: "npm@marcosvrs.com"
        api_key: $NPM_API_KEY
        skip_cleanup: true
        on:
          tags: true